Repository sanger/sequencescape, pull requests merged in 2019-11, with the labels that each got.

#2399 Link to other guides
  app/views/asset_audits/index.html.erb
  app/views/homes/show.html.erb
  app/views/shared/metadata/edit/_study.html.erb
Labels: enhancement, no uat

#2408 Create initial Issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/research-task.md
Labels: enhancement, no uat

#2414 Gpl177 create tube rack manifest
  Gemfile
  Gemfile.lock
  app/controllers/sdb/sample_manifests_controller.rb
  app/helpers/sdb/sample_manifests_helper.rb
  app/models/racked_tube.rb
  app/models/sample_manifest.rb
  app/models/sample_manifest/core_behaviour.rb
  app/models/sample_manifest/shared_tube_behaviour.rb
  app/models/sample_manifest/tube_rack_behaviour.rb
  app/models/tube.rb
  app/models/tube_rack.rb
  app/models/tube_rack/purpose.rb
  app/sample_manifest_excel/sample_manifest_excel/worksheet/data_worksheet.rb
  app/sequencescape_excel/sequencescape_excel/helpers/worksheet.rb
  app/views/sdb/sample_manifests/new.html.erb
  app/views/shared/_create_manifests_side_links.html.erb
  config/sample_manifest_excel/columns.yml
  config/sample_manifest_excel/manifest_types.yml
  db/migrate/20191024143941_create_racked_tubes.rb
  db/migrate/20191031154006_add_tube_rack_purpose_to_sample_manifest.rb
  db/schema.rb
  features/6048016_correct_bug_qc_state_scannedintolab.feature
  features/reception.feature
  features/sample_manifest/sample_manifest.feature
  features/sample_manifest/sample_tube_manifest.feature
  lib/tasks/limber.rake
  spec/data/sample_manifest_excel/columns.yml
  spec/data/sample_manifest_excel/manifest_types.yml
  spec/factories/purpose_factories.rb
  spec/factories/racked_tube.rb
  spec/factories/sample_manifest_factories.rb
  spec/factories/tube_rack.rb
  spec/features/sample_manifests/create_manifest_spec.rb
  spec/models/racked_tube_spec.rb
  spec/models/tube_rack_spec.rb
  spec/models/tube_spec.rb
  spec/sample_manifest_excel/worksheet_spec.rb
Labels: enhancement, uat required

#2420 Fix for failing reception view cucumber feature tests
  features/6048016_correct_bug_qc_state_scannedintolab.feature
  features/reception.feature
Labels: bug, no uat
